version: '3.7'

services:
  web:
    build:
       context: ./project
       dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - redis

  redis:
    image: redis:alpine

  celery:
    build: ./project
    command: celery -A core worker -l info
    volumes:
      - ./project/:/usr/src/app/
    env_file:
      - ./.env.prod
    depends_on:
      - redis

  celery-beat:
    build: ./project
    command: celery -A core beat -l info
    volumes:
      - ./project/:/usr/src/app/
    env_file:
      - ./.env.prod
    depends_on:
      - redis

  dashboard:
    build: ./project
    command:  flower -A core --port=5555 --broker=redis://redis:6379/0
    ports:
        - 5555:5555
    env_file:
      - ./.env.prod
    depends_on:
        - web
        - redis
        - celery

