version: '3'

volumes:
  static-volume:
  media-volume:

services:
  web:
    build: lmsapi
    expose:
      - 80
    env_file:
      - ./.env
    volumes:
      - ./lmsapi/:/usr/src/app/
      - static-volume:/usr/src/app/static
      - media-volume:/usr/src/app/media


networks:
  default:
    external:
      name: nginx-proxy