version: '3.7'

services:
  app:
    build: ./app
    ports:
      - 8000:8000
    environment:
      - DB_HOST=192.168.43.10
      - DB_NAME=lms
      - DB_USER=devroot
      - DB_PASS=fbJWd8pDGM7BQ5
      - DB_PORT=3306
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    volumes:
      - ./app/:/usr/src/app/
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis

  redis:
    image: redis:alpine

  celery:
    build: ./app
    command: celery -A app worker -l info
    volumes:
      - ./app/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  celery-beat:
    build: ./app
    command: celery -A app beat -l info
    volumes:
      - ./app/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  dashboardn:
    build: ./app
    command: flower -A app --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis
      - celery