version: '3.7'

services:
  web:
    build: ./app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    volumes:
      - ./app/:/usr/src/app/
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis

  redis:
    image: redis:alpine

  celery:
    build: ./app
    command: celery -A app worker -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  celery-beat:
    build: ./app
    command: celery -A app beat -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - redis

  dashboard:
    build: ./app
    command:  flower -A app --port=5555 --broker=redis://redis:6379/0
    ports:
        - 5555:5555
    env_file:
      - ./.env.dev
    depends_on:
        - web
        - redis
        - celery