version: '3.7'

services:
  web:
    build: lmsapi
    expose:
      - 80
    env_file:
      - ./.env
    volumes:
      - ./lmsapi/:/usr/src/app/


networks:
  default:
    external:
      name: nginx-proxy